# -*- coding: utf-8 -*-
"""demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148BFodSvUY4bkKmKOIaH085BqaE0Iuia

Imports
"""

!git clone https://github.com/bmsubra25/qu_fem_in_qualtran
!git clone https://github.com/ichuang/pyqsp
!pip install -U qualtran
!pip install pennylane cirq
!pip install scikit-fem

"""Imports"""

import qu_fem_in_qualtran
from qu_fem_in_qualtran import *
from itertools import product as cartproduct
import math
import random
from typing import *
from qu_fem_in_qualtran.qu_fem import construct_source_vector_diag
from qu_fem_in_qualtran.mqet import MQET
from qu_fem_in_qualtran.quantum_linear_systems import qlsp_solver_prepared
from qu_fem_in_qualtran.quantum_linear_systems import prep_vector
import cirq
import numpy as np
import pennylane as qml
import pyqsp
import qualtran
import qualtran.simulation as sim
import sympy
from numpy.polynomial import Chebyshev
from qualtran.bloqs.bookkeeping import Partition
from scipy.linalg import sqrtm
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    CtrlSpec,
    QAny,
    QBit,
    QInt,
    QUInt,
    Register,
    Signature,
    cirq_interop,
)
from sympy import legendre
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import (
    CNOT,
    GlobalPhase,
    Hadamard,
    IntEffect,
    OneEffect,
    OneState,
    PlusState,
    Rz,
    SGate,
    Swap,
    TGate,
    XGate,
    ZeroState,
    ZGate,
)
from qualtran.bloqs.basic_gates import Identity
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    LinearCombination,
    Product as BlockEncodingProduct,
    TensorProduct,
    Unitary,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from itertools import combinations
from qualtran.cirq_interop import CirqGateAsBloq
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.bloqs.state_preparation import PrepareUniformSuperposition
from sympy import diff
import sympy as sp
from sympy import degree
import skfem

"""Helper Functions"""

def generate_vars(d):
  string = ""
  for i in range(d):
    string += f"x_{i} "
  return sp.symbols(string)

def generate_lagrange_basis_1D(p, v, index):
  poly = 1
  for m in range(p+1):
    if m != index:
      poly = poly * (v -  m/p) / (index / p - m/p)
  return sp.Poly(poly, v)

def generate_lagrange_basis(p, indices):
  vars = generate_vars(len(indices))
  func = 1
  for i in range(len(indices)):
    func = func * generate_lagrange_basis_1D(p, vars[i], indices[i])
  return sp.Poly(func, vars)
generate_lagrange_basis(2, [0,1])

"""Mesh Creation/Mesh Parameter Setting"""

# number of nodes per element
nen = 4
# number of nodal points total
numnp = 4096
# bits to represent these
nen_bits = math.ceil(math.log(nen, 2))
numnp_bits = math.ceil(math.log(numnp, 2))
# dimension of space
d = 2
# interval setting
interval_start = 0.0
interval_end = 10.0
# mesh creation
space = []
for i in range(d):
  space.append(np.linspace(interval_start,interval_end,int(numnp ** (1/d))))
mesh = skfem.MeshQuad.init_tensor(*space)
numel = mesh.t.shape[1]
numel_bits = math.ceil(math.log(numel, 2))
IX = mesh.t
reference = mesh.init_refdom()

"""Function Definitions"""

nodal_reference_functions = []
for col in range(nen):
  coords = []
  for row in range(len(list(reference.p))):
    coords.append(reference.p[row][col])
  nodal_reference_functions.append(generate_lagrange_basis(int(math.log(nen, 2)-1), coords))
# int(dN_i * dN_j)
nodal_basis_map_k = []
# int(N_i * N_j)
nodal_basis_map_m = []

for j in range(len(nodal_reference_functions)):
  for k in range(len(nodal_reference_functions)):
    nodal_basis_map_k.append(diff(nodal_reference_functions[j])*diff(nodal_reference_functions[k]))

for j in range(len(nodal_reference_functions)):
  for k in range(len(nodal_reference_functions)):
    nodal_basis_map_m.append(nodal_reference_functions[j]*nodal_reference_functions[k])

"""Poisson's Problem"""

x = sp.symbols("x")
source_function = sp.poly(x ** 2,x)
construct_source_vector_diag(5, nen, numel, numnp, nen_bits, numel_bits, numnp_bits, IX, d, nodal_reference_functions, source_function)
