# -*- coding: utf-8 -*-
"""Multivariate Quantum Eigenvalue Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rF5sYCwb78zPK0Udqhciwgwqfctmz1-y

Installation
"""

!git clone https://github.com/ichuang/pyqsp
!pip install pennylane cirq
!pip install -U qualtran

"""Imports"""

from numpy.polynomial import Chebyshev
from numpy.polynomial.chebyshev import cheb2poly
from numpy.polynomial import Polynomial
import qualtran
import sympy as sp
import scipy
from qualtran import *
import qualtran
from qualtran import *
from qualtran.bloqs import *
import math
import numpy as np
from qualtran import Bloq, BloqBuilder, QUInt, QAny
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import Swap
from qualtran.bloqs.block_encoding import BlockEncoding, Unitary
from qualtran.bloqs.basic_gates import XGate, ZGate, Identity
from qualtran import Bloq, CompositeBloq, BloqBuilder, Signature, Register
from qualtran import QBit, QInt, QUInt, QAny
from qualtran.drawing import show_bloq, show_call_graph, show_counts_sigma
from typing import *
from qualtran.bloqs.arithmetic import *
import numpy as np
import sympy
from qualtran.bloqs.block_encoding import LinearCombination
import cirq
from qualtran.bloqs.block_encoding import Product as BlockEncodingProduct
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran import cirq_interop
from qualtran.bloqs.block_encoding import TensorProduct
import qualtran.simulation as sim
!pip show qualtran
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from itertools import product
from numpy.polynomial import Chebyshev
from functools import partial

"""Q_s Helper"""

def generate_q_s(r, g, s, prod, variables):
  overall = 1
  bounds = [(variables[i],-1,1) for i in range(r)]
  integral = sympy.integrate(prod,*bounds)
  for k in range(r):
      delta = 1 if s[k] == 0 else 0
      coef = (2 - delta)/sp.pi
      overall = overall*coef
  return overall*integral

"""Infinity Norm Finder"""

def infinity_norm(p, range):
  roots = p.deriv().roots()
  return max([abs(p(root)) for root in roots if range[0] <= root and root <= range[1]] + [abs(p(range[0]))]+[abs(p(range[1]))])

"""Core MQET"""

# Assues g is a sympy polynomial
def MQET(commuting_operators, D, r, g):
  u_s_a_list = []
  B = []
  # Creates symbols for use
  symbols_str = ""
  for i in range(r+1):
    symbols_str = symbols_str + f"x_{i} "
  vars = sympy.symbols(symbols_str)
  for s in product(range(D),repeat = r):
    p_s = []
    div_functions = []
    for s_k in s:
      p_s.append(Chebyshev.basis(s_k))
    integrand_functions = [g]+[sp.chebyshevt(s[i],vars[i])/(sp.Poly(sp.sqrt(1-vars[i]**2), vars[i])) for i in range(r)]
    prod = 1
    for func in integrand_functions:
      prod = prod * func
    q_s = sp.Poly(generate_q_s(r,g,s,prod, vars),vars[-1])
    coeffs = np.array(q_s.all_coeffs(),dtype = complex)[::-1]
    q_s = Polynomial(coeffs)
    # Make B_s
    B_s = infinity_norm(q_s, [-1,1])
    for k in range(len(p_s)):
      B_s = B_s * infinity_norm(p_s[k], [-1,1])
    B.append(B_s)
    # Hats
    p_s_hats = []
    for k in range(len(p_s)):
      p_s_hats.append(p_s[k]/infinity_norm(p_s[k], [-1,1]))
    q_s_hat = q_s/infinity_norm(q_s, [-1,1])
    # Creates q_s_hat block encoding
    q_s_hat_be = GeneralizedQSP.from_qsp_polynomial(commuting_operators[r],tuple(q_s_hat.coef))
    # Creates block encodings
    p_block_encodings = []
    for k in range(len(p_s_hats)):
      standard_poly = cheb2poly(p_s_hats[k].coef)
      p_block_encodings.append(GeneralizedQSP.from_qsp_polynomial(commuting_operators[k], tuple(standard_poly)))
    # Create U_(s,a)
    combined_list = p_block_encodings[::-1]+[q_s_hat_be]
    u_s_a_list.append(Product(tuple(combined_list)))
  return LinearCombination(block_encodings = tuple(u_s_a_list), lambd = tuple(B), lambd_bits = 3)

"""testing"""
