# -*- coding: utf-8 -*-
"""QuFEM in Qualtran

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFfoKH_PYpqLvXG8kmXP1TFsvJqckQcn

Imports
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U qualtran

import qualtran
from qualtran import *
from qualtran.bloqs import *
import math
import numpy as np
from qualtran import Bloq, BloqBuilder, QUInt, QAny
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import Swap
from qualtran.bloqs.block_encoding import BlockEncoding, Unitary
from qualtran.bloqs.basic_gates import XGate, ZGate, Identity
from qualtran import Bloq, CompositeBloq, BloqBuilder, Signature, Register
from qualtran import QBit, QInt, QUInt, QAny
from qualtran.drawing import show_bloq, show_call_graph, show_counts_sigma
from typing import *
from qualtran.bloqs.arithmetic import *
import numpy as np
import sympy
from qualtran.bloqs.block_encoding import LinearCombination
import cirq
from qualtran.bloqs.block_encoding import Product as BlockEncodingProduct
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran import cirq_interop
from qualtran.bloqs.block_encoding import TensorProduct
import qualtran.simulation as sim
!pip show qualtran
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from itertools import product
from numpy.polynomial import Chebyshev

"""Position Operators/Q"""

class z_i(Bloq):
  def __init__(self, n, i):
    self.n = n
    self.i = i
  @property
  def signature(self):
    return Signature([Register("point",QAny(self.n))])
  def build_composite_bloq(self, bb, *, point):
    point_array = bb.split(point)
    point_array[self.n - self.i -1] = bb.add(ZGate(),q = point_array[self. n - self.i -1])
    point = bb.join(point_array, dtype = QAny(self.n))
    return {"point": point}

def build_x(n):
  N = 2**n
  coeffs = [(N-1)/2]
  unitaries = [Unitary(Identity(n))]
  for i in range(n):
    coeffs.append(-(0.5 * (2**i)))
    unitaries.append(Unitary(z_i(n,i)))
  return LinearCombination(tuple(unitaries),lambd = tuple(coeffs), lambd_bits = 3)

class x_i(Bloq):
  def __init__(self, d, n, i):
    self.d = d
    self.n = n
    self.i = i
    self.x = build_x(n)
  @property
  def signature(self):
    registers = [Register(f"point_{i}", QAny(self.n)) for i in range(self.d)]
    registers.append(Register("ancilla", QAny(self.x.ancilla_bitsize) ))
    registers.append(Register("resource", QAny(self.x.resource_bitsize)))
    return Signature(registers)
  def build_composite_bloq(self, bb, *,ancilla, resource, **points):
    print(points)
    points[f"point_{self.d - self.i - 1}"], ancilla, resource = bb.add(self.x, system = points[f"point_{self.d-self.i-1}"], ancilla = ancilla, resource = resource)
    return {"ancilla": ancilla, "resource": resource, **points}

"""Mesh Connectivity Block Encoding"""

class o_l_numel(Bloq):
  def __init__(self, numel, numel_bits):
    self.numel = numel
    self.numel_bits = numel_bits
  @property
  def signature(self):
    return Signature([Register("el", QUInt(self.numel_bits)),Register("flag", QBit())])
  def build_composite_bloq(self, bb, *, el, flag):
    numel_reg = bb.allocate(dtype = QUInt(self.numel_bits))
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits, dtype = QUInt(self.numel_bits))
    numel_reg, el , flag = bb.add(GreaterThan(a_bitsize = self.numel_bits, b_bitsize = self.numel_bits), a = numel_reg, b = el, target = flag)
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits)
    bb.free(numel_reg)
    return {"el": el, "flag": flag}

class o_ix(Bloq):
  def __init__(self,nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX):
    self.nen_bits = nen_bits
    self.width = max(numel_bits,numnp_bits)
    inv = [[0 for _ in range(numnp)] for _ in range(nen)]
    for j in range(nen):
      for el in range(numel):
        inv[j][IX[j][el]] = el
    self.indexer = QROM([np.array(IX)],(self.nen_bits,self.width), (self.width,))
    self.inverse = QROM([np.array(inv)],(self.nen_bits,self.width),(self.width,))
  @property
  def signature(self):
    return Signature([Register("j", QUInt(self.nen_bits)),
                      Register("el", QUInt(self.width))])
  def build_composite_bloq(self,bb,*, j, el):
    ancilla_reg = bb.allocate(self.width)
    j, el, ancilla_reg = bb.add(self.indexer, selection0 = j, selection1 = el, target0_ = ancilla_reg)
    el, ancilla_reg = bb.add(Swap(bitsize = self.width),x= el, y = ancilla_reg)
    j, el, ancilla_reg = bb.add(self.inverse, selection0 =j, selection1 = el, target0_ = ancilla_reg)
    bb.free(ancilla_reg)
    return {"j": j, "el": el}

class a_j_block_encoding(BlockEncoding):
  def __init__(self,nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX, j):
    self.oracle_ix = o_ix(nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX)
    self.width = max(numel_bits,numnp_bits)
    self.oracle_l_numel = o_l_numel(numel,self.width)
    self.numel = numel
    self.nen_bits = nen_bits
    self.j = j
  @property
  def signature(self):
    return Signature([Register("system", QUInt(self.width)),Register("ancilla", QAny(1))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.width
  def build_composite_bloq(self,bb, *, system, ancilla):
    # Allocating j bits
    j = bb.allocate(dtype = QUInt(self.nen_bits))
    j_reg_bits = bb.split(j)
    for index in range(self.nen_bits):
      if (self.j >> index) & 1:
        j_reg_bits[self.nen_bits - index - 1] = bb.add(XGate(), q = j_reg_bits[self.nen_bits - index - 1])
    j = bb.join(j_reg_bits, dtype = QUInt(self.nen_bits))
    # Performing Computation
    system, ancilla  = bb.add(self.oracle_l_numel,el = system, flag = ancilla)
    ancilla= bb.add(XGate(), q = ancilla)
    j, system = bb.add(self.oracle_ix,j = j,  el = system)
    # Uncomputing j
    j_reg_bits = bb.split(j)
    for index in range(self.nen_bits):
      if (self.j >> index) & 1:
        j_reg_bits[self.nen_bits - index - 1] = bb.add(XGate(), q = j_reg_bits[self.nen_bits - index - 1])
    j = bb.join(j_reg_bits, dtype = QUInt(self.nen_bits))
    bb.free(j)
    return {"system": system, "ancilla": ancilla}

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, system, ancilla):
    system, ancilla = bb.add(self.block_encoding.adjoint(),system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

class a_jk_block_encoding(BlockEncoding):
  def __init__(self,nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX,j, k):
    a_j = a_j_block_encoding(nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX, j)
    a_k = a_j_block_encoding(nen,numel,numnp,nen_bits,numel_bits,numnp_bits,IX, k)
    self.a_jk = BlockEncodingProduct((a_j,AdjointBlockEncoding(a_k)))
    self.width = max(numel_bits,numnp_bits)
    self.nen_bits = nen_bits
  @property
  def alpha(self):
    return self.a_jk.alpha
  @property
  def ancilla_bitsize(self):
    return self.a_jk.ancilla_bitsize
  @property
  def epsilon(self):
    return self.a_jk.epsilon
  @property
  def resource_bitsize(self):
    return self.a_jk.resource_bitsize
  @property
  def signal_state(self):
    return self.a_jk.signal_state
  @property
  def system_bitsize(self):
    return self.a_jk.system_bitsize
  @property
  def signature(self):
    return self.a_jk.signature
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.a_jk, system = system, ancilla = ancilla,)
    return {"system": system, "ancilla": ancilla}

"""K and M Construction"""



"""MQET"""



"""QLSP"""
