# -*- coding: utf-8 -*-
"""quantum_linear_systems

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYHH8S3WaIDCYkC7NsY-CE5oecz7RV3j

Installation
"""

# Commented out IPython magic to ensure Python compatibility.
"""Solves BE(A) @ |v>|0> = b for A< v, b"""
# %pip install pennylane cirq qualtran

"""Imports"""

!git clone https://github.com/ichuang/pyqsp
import sys
sys.path.insert(0, './pyqsp')

import math
from qualtran.bloqs.basic_gates import Rz
import random
from itertools import product
from typing import *
import numpy as np
import sympy
import cirq
from scipy.linalg import sqrtm
from numpy.polynomial import Chebyshev
import qualtran
from qualtran.bloqs.basic_gates import SGate
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    Signature,
    Register,
    CtrlSpec,
    QBit,
    QInt,
    QUInt,
    QAny,
    cirq_interop,
)
import qualtran.simulation as sim
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.basic_gates import (
    Swap,
    XGate,
    ZGate,
    Identity,
    ZeroState,
    OneState,
    OneEffect,
    PlusState,
    CNOT,
)
from qualtran.bloqs.basic_gates import IntEffect
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    Unitary,
    LinearCombination,
    TensorProduct,
    Product as BlockEncodingProduct,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.cirq_interop import CirqGateAsBloq
import pennylane as qml
import pyqsp
from pyqsp.angle_sequence import QuantumSignalProcessingPhases
from pyqsp.poly import PolyOneOverX
from qualtran.bloqs.basic_gates import Hadamard

"""Adjoint Block Encoding"""

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, system, ancilla, resource):
    system, ancilla, resource = bb.add(self.block_encoding.adjoint(),system = system, ancilla = ancilla, resource = resource)
    return {"system": system, "ancilla": ancilla, "resource": resource}

"""O Block Encoding(Hermitian Embedding)"""

# matrix is a block encoding already
class c_embed(Bloq):
  def __init__(self, n, matrix):
    self.a = matrix
    self.a_t = AdjointBlockEncoding(matrix)
    self.n = n
    self.ancilla_bitsize = self.a.ancilla_bitsize
    self.resource_bitsize = self.a.resource_bitsize
  @property
  def signature(self):
    return Signature([Register("ancilla", QAny(self.a.ancilla_bitsize)),Register("resource", QAny(self.a.resource_bitsize)), Register("zero",QAny(1)), Register("vector",QAny(self.a.system_bitsize))])
  def build_composite_bloq(self, bb, *, ancilla, resource, zero, vector):
    a_controlled = self.a.controlled(CtrlSpec())
    a_t_controlled = self.a_t.controlled(CtrlSpec())
    # Applies |1> |v> -> |1> |A @ v>. If the input is |0> |v> it will return |0> |v>
    zero, vector, ancilla, resource, = bb.add(a_controlled, ancilla = ancilla, resource = resource, ctrl = zero, system = vector)
    # X's the zero bit so that if the input was 0 it will be 1 now
    zero = bb.add(XGate(), q = zero)
    # applies |1> |v> -> |1> |A^t @ v>. If the original input was 1, it will be 0 now so the operation will
    # not be performed
    zero, vector,ancilla, resource,  = bb.add(a_t_controlled, ancilla = ancilla, resource = resource, ctrl = zero, system = vector)
    return {"ancilla": ancilla, "resource": resource, "zero": zero, "vector": vector, }

"""QSVT Bloq"""

# Takes in a block encoding of a block encoding
class QSVT(Bloq):
  def __init__(self, block_encoding, angles):
    self.block_encoding = block_encoding
    self.adjoint_block_encoding = self.block_encoding.adjoint()
    self.angles = angles
  @property
  def signature(self):
    return self.block_encoding.signature
  def build_composite_bloq(self, bb, *, ancilla, resource, zero, vector):
    ancilla = bb.add(Rz(-2 * self.angles[0]), q = ancilla)
    adj = False
    for angle in self.angles[1:]:
      if adj:
        ancilla, resource, zero, vector = bb.add(self.adjoint_block_encoding, vector = vector, ancilla = ancilla, resource = resource, zero = zero)
      else:
         ancilla, resource, zero, vector = bb.add(self.block_encoding, vector = vector, ancilla = ancilla, resource = resource, zero = zero)
      adj = not adj
      ancilla = bb.add(Rz(-2*angle), q = ancilla)
    return {"ancilla": ancilla, "resource": resource, "zero": zero, "vector": vector}

"""QSVT(Approximation of c/x on singular values)"""

def return_qsvt(H):
  coeffs, scale = pyqsp.poly.PolyOneOverX().generate(return_scale = True)
  angles_qsp = pyqsp.angle_sequence.QuantumSignalProcessingPhases(coeffs)
  angles_qsvt = qml.transform_angles(angles_qsp, "QSP","QSVT")
  return QSVT(H, angles_qsvt)

"""QLSP Solver"""

def prep_b(bb,b, phases):
    phase_bitsize = 5
    prepare_b = StatePreparationViaRotations(phase_bitsize = phase_bitsize, state_coefficients = tuple(b))
    phase_gradient = bb.add(PhaseGradientState(phase_bitsize))
    state, phase_gradient = bb.add(prepare_b, target_state = phases, phase_gradient = phase_gradient)
    bb.add(PhaseGradientState(bitsize=phase_bitsize).adjoint(), phase_grad=phase_gradient)
    return state
# Assumes A and b are padded to a power of 2
def qlsp_solver(n, A, b, bb):
  vector = prep_b(bb,b,bb.allocate(int(math.log(len(b),2))))
  # Assumes A is a block encoded matrix
  c_embed_a = c_embed(n, A)
  # Performs an approximation of 1/x on the singular values of the hermitian embedding of A
  c_embed_inverse =  return_qsvt(c_embed_a)
  # Allocating the control qubit for applying the original and the adjoint
  ctrl = bb.allocate(1)
  controlled_c_embed_inverse = c_embed_inverse.controlled(CtrlSpec())
  controlled_c_embed_inverse_t = c_embed_inverse.adjoint().controlled(CtrlSpec())
  # hadamarding
  ctrl = bb.add(Hadamard(), q = ctrl)
  # allocating and then joining the qubits to be fed into c_embed_inverse
  ancilla = bb.allocate(c_embed_a.ancilla_bitsize)
  resource = bb.allocate(c_embed_a.resource_bitsize)
  zero = bb.allocate(1)
  # applies QSVT circuit and its adjoint to remove the extra polynomial
  ctrl, ancilla, resource, zero, vector = bb.add(controlled_c_embed_inverse,ctrl = ctrl, ancilla = ancilla, resource = resource, zero = zero, vector = vector)
  ctrl = bb.add(XGate(), q = ctrl)
  ctrl, ancilla, resource, zero, vector = bb.add(controlled_c_embed_inverse_t,ctrl = ctrl, ancilla = ancilla, resource = resource, zero = zero, vector = vector)
  # Projects ancilla and resource vectors down
  ctrl = bb.add(Hadamard(), q = ctrl)
  bb.add(IntEffect(0, 1), val = ctrl)
  bb.add(IntEffect(0, c_embed_a.ancilla_bitsize), val = ancilla)
  bb.add(IntEffect(0, c_embed_a.resource_bitsize), val = resource)
  bb.add(IntEffect(1, 1), val = zero)
  circuit = bb.finalize(vector = vector)
  return circuit

# Sample test
"""A = LinearCombination(block_encodings = (Unitary(Identity()),Unitary(SGate())), lambd = (1.0,1.0), lambd_bits = 1)
b = np.array([1,1])/ np.sqrt(2)
n = 2
bb = BloqBuilder()
sol1 = qlsp_solver(n,A,b,bb).tensor_contract()
Identit = np.array([[1,0],[0,1]], dtype = complex)
SGat = np.array([[1,0],[0,1j]], dtype = complex)
comb = Identit + SGat
print(sol1)
print(np.linalg.inv(comb) @ b)
sol1 / (np.linalg.inv(comb) @ b)"""
